<a href="https://colab.research.google.com/github/Bhargavi-Panuganti/ML_Notebook/blob/main/week2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
(9,)
1
9
int64


In [ ]:
print(arr[-1])
print(arr[1:3])
print(arr[2:5])
print(arr[:3])
print(arr[-3:])
print(arr[:-2])
print(arr[::-1])

9
[2 3]
[3 4 5]
[1 2 3]
[7 8 9]
[1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1]


In [ ]:
b = np.array([[1, 2, 3,4],
              [5, 6,7,8],[9,10,11,12]])
print(b.shape)   # (2, 3)
print(b.ndim)    # 2
print(b.dtype)   # int64
print(b.size)    # 6

(3, 4)
2
int64
12


In [ ]:
c=np.zeros((2, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
d=np.arange(0,10,3)
print(d)

[0 3 6 9]


In [ ]:
e=np.linspace(0,1,5)
# 5 evenly spaced from 0 to 1
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
f=np.arange(12).reshape(3,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(b[0, :])
print(b[:, 2])
print(b[1:3, :])
print(b[0:2, 1:3])
print(b[-1, :])
print(b[:, -1])

[1 2 3 4]
[ 3  7 11]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[ 9 10 11 12]
[ 4  8 12]


In [ ]:
# Boolean Indexing
arr=np.array([40,50, 60, 70, 80])
print(arr[arr > 50] )
print(arr[(arr > 20) & (arr < 60)])
print(arr[arr % 2 == 0] )

[60 70 80]
[40 50]
[40 50 60 70 80]


In [ ]:
# np.where(condition, x, y) — returns x where condition is True, y where False. Each element is tested independently.

arr = np.array([5, 18, 3, 42, 11, 7, 29, 1])
# np.where(arr > 10, arr, 0)
# np.where(arr > 10, arr, -1)
# np.where(arr > 10, 1, 0)
np.where(arr % 2 == 0, 'E', 'O')

array(['O', 'E', 'O', 'E', 'O', 'O', 'O', 'O'], dtype='<U1')

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.dot(a, b))

70


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])    # shape (2, 3)

B = np.array([[7,  8],
              [9,  10],
              [11, 12]])     # shape (3, 2)

print(np.dot(A, B))
print(A @ B )  # same as np.dot(A, B)

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]
